package com.example.project3.bank;

/**
 * Provide a sequence of integers for the account numbers.
 * For Project 1 & 2 Spring 2025
 * @author Lily Chang
 */
public class Random
{
    private static final int SEED = 9999;
    private int[] sequence;
    private int next;

    /**
     * The first 100 integers generated by java.util.Random with SEED and nextInt(SEED)
     * @param seed dummy parameter, so the students don't need to change their code.
     */
    public Random(int seed)
    {
        sequence = new int[] {7410, 6899, 432, 9048, 3147, 2615, 1866, 4127, 2742, 7979,
                7003, 7458, 7432, 6682, 4566, 9464, 3095, 3688, 3343, 1134,
                9714, 5089, 9232, 2381, 6189, 1888, 3013, 1126, 5559, 3394,
                7936, 9991, 7836, 863, 8091, 3461, 6294, 4024, 1404, 3098,
                2983, 2419, 8626, 3956, 6767, 8267, 6801, 7020, 1795, 1808,
                2683, 1827, 8610, 3994, 2269, 8389, 1223, 3401, 253, 3642,
                760, 6614, 8210, 7443, 2642, 1967, 1850, 6248, 6315, 5242,
                8827, 2721, 4271, 4247, 8652, 2893, 1552, 7551, 68, 4746,
                8636, 7817, 9165, 7555, 8832, 3391, 6627, 6940, 344, 7917,
                7434, 8835, 1262, 1612, 9130, 3891, 9290, 823, 2928, 1346
        };
    }

    /**
     * Return the next integer in the sequence.
     * @param seed dummy parameter.
     * @return the next integer in the sequence.
     */
    public int nextInt(int seed)
    {
        return sequence[next++];
    }

    public static void main(String[] args)
    {
        /*
        Random random = new Random(SEED);
        for (int i = 0; i < 100; i++)
            System.out.print(random.nextInt(SEED) + ",");
    */
    }

}
